{% set name = "libblasfeo" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/giaf/blasfeo/archive/refs/tags/{{ version }}.tar.gz
    sha256: c33eb6467a90d6075a8db34e5ab239ecdda38c5261ae096def122fe7a0f98780

build:
  # windows and macos are supported on the master branch, as soon as a new version is released
  # they can be packaged (see https://github.com/giaf/blasfeo/issues/181)
  skip: True  # [win or osx]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - pkg-config
    - ninja

test:
  commands:
    - test -f $PREFIX/include/blasfeo.h  # [unix]
    - test -f $PREFIX/lib/libblasfeo${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/cmake/blasfeoConfig.cmake   # [unix]
    - if not exist %PREFIX%\\Library\\cmake\\blasfeoConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_INC%\\blasfeo.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\blasfeo.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\blasfeo.dll exit 1  # [win]

about:
  home: https://github.com/giaf/blasfeo
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: Basic linear algebra subroutines for embedded optimization

extra:
  feedstock-name: blasfeo
  recipe-maintainers:
    - traversaro
